#!/bin/bash

#vars

number=$1
serwer=$2

#check number

re='^[0-9]+$'
if ! [[ $number =~ $re ]] ; then
      echo "error: Not a number"
      exit 1
fi

if ! [ -p "/home/studinf/$serwer/serwerfifo" ] ; then
	echo "error: serwer problem"
	echo "/home/studinf/$serwer/serwerfifo" 
        exit 1
fi

if ! [ -p "/$HOME/klientfifo" ] ; then
	mkfifo "/$HOME/klientfifo"
fi

echo "$number $HOME" > "/home/studinf/$serwer/serwerfifo"

#read line < "/$HOME/klientfifo
while read line; do echo "$line"; done<"/$HOME/klientfifo" 
echo $line

exit 0
