#!/bin/bash

trap '' SIGHUP
trap '' SIGTERM
#trap exit 1 SIGUSR1

klient=""

if [ "$1" ]; then

		if [ "$2" ]
		then
		klient="$2"

			if [ -p "/$klient/klientfifo" ] ; then
			echo $(($1 + $1)) > "/$klient/klientfifo"
			fi
		fi
else
		if ! [ -p "/$HOME/serwerfifo" ] ; then
			mkfifo "/$HOME/serwerfifo"
		fi
		
		while true
		do
			if read line < "/$HOME/serwerfifo" ; then
				./serwer $line
			fi
		done
fi
			
