#!/bin/bash

#zmienne

declare -i foundfiles
PROCESLIST=
foundfiles=0

#sprawdz argumenty

if [ "$#" -lt 2 ]
then
	echo "Za malo argmetnow"
	exit
else
	file=$1
	folder=$2
	status=$3
fi

#szukaj katalogow

for i in $(find "$folder" -maxdepth 1 -mindepth 1 -type d )
do
	./szukaj $file $i "1" &
	PROCESLIST+=("$!")
done

#czeaknie na procesy

for i in "${PROCESLIST[@]}"
do
	if [  "$i" ]
	then
	wait "$i"
	foundfiles=$((foundfiles+$?))
	fi
done

#szukanie plikow

for i in $(find "$folder" -maxdepth 1 -mindepth 1 -type f -printf "%f\n")
do
	if [ "$i" == "$file" ]
	then 
		echo "FOUND: Found '$i' in folder '$folder'"
		foundfiles=$((foundfiles+1))
	fi
done

#podsumowanie z arg wyjsciowymi wszystkich procesow potomnyhc

	if [ -z "$status" ]
	then
		if [ "$foundfiles" -eq 0 ]
		then
		echo "Nie znaleziono"
		fi
	fi

exit "$foundfiles"
