#!/bin/bash

#zmienne

declare -i files
tempint=0
PROCESLIST=

#sprawdz argumenty


if [ "$#" -lt 2 ]
then
	echo "Za malo argmetnow"
	exit
else
	plik=$1
	katalog=$2
fi
	files=$((files+returnCode))
#szukaj

	declare -i num
	num=0

for i in $(find "$katalog" -maxdepth 1 -mindepth 1 -type d )
do
	./szukaj $plik $i "1" &
    	files=$((files+$?))
	PROCESLIST+=("$!")
done
	
for i in "${PROCESLIST[@]}"
do
	if [  "$i" ]
	then
	wait "$i"
	files=$((files+$?))
	fi
done

for i in $(find "$katalog" -maxdepth 1 -mindepth 1 -type f -printf "%f\n")
do
	if [ "$i" == "$plik" ]
	then 
		echo "FOUND: Found '$i' in folder '$katalog'"
		files=$((files+1))
	fi
done
	if [ -z "$3" ]
	then
		if [ "$files" -eq 0 ]
		then
		echo "Nie znaleziono"
		fi
	fi

exit "$files"
